---
title: "sim-confidence-estimation_power-analysis"
author: "Matt Jaquiery"
date: "20/01/2020"
output: html_document
---

```{r echo = F}
library(tidyverse)
library(ggpubr)
library(broom)
library(BayesFactor)
library(prettyMD)
library(knitr)
library(parallel)

opts_chunk$set('echo' = F)

set.seed(20191216)

# Plot setup
theme_set(theme_light() + 
            theme(panel.grid.major.x = element_blank()))

rDir <- "http://localhost/ExploringSocialMetacognition/data/public/"
testData <- T

studyVersion <- "0-0-10"
studyName <- "confidenceExploration"

exclude <- list(
  maxTrialRT = 60000,    # trials take < 1 minute
  minTrials = 11,        # at least 11 trials completed
  minChangeRate = .1     # some advice taken on 10%+ of trials
  ) 

skipLoadData <- F

source("src/02_Exclusions.R")

```

## Data 

Here's the data we'll be playing with. It's generated by multiple runs of our integration tests.

```{r}

AdvisedTrial

```

## Parameters

We need to set up some parameters to explore. For now we'll just use different levels of the effect size, but we specify some other stuff anyway.

```{r}

params <- tibble(
  agentInsensitivitySD = 8,
  agentConfidence = 2,
  agentConfidenceSD = 4,
  agentEgoBias = .7, 
  agentEgoBiasSD = .2,
  agentEffectSize = seq(.0, .2, by = .025),
  agentEffectSizeSD = .05
)

params <- crossing(tibble(nAgents = seq(10, 50, 5)), params)

params

```

## Simulations

Now we run the simulations with those parameters.

```{r}
source('src/sim-confidence-estimation.R')

sim <- powerAnalysisCE(AdvisedTrial, params)

peek <- cbind(
  sim$parameters,
  map_dfr(sim$models$analysis, rbind)
)

peek

```

## Plot the relationship between effect size and BF/p

```{r}

ggplot(peek, aes(x = agentEffectSize, y = BF, colour = parameter)) +
  geom_hline(yintercept = 3) + 
  geom_hline(yintercept = 1/3) +
  geom_smooth(method = 'lm') +
  stat_cor() + 
  geom_point() +
  scale_y_log10() +
  labs(title = "BF for influence t-test",
       subtitle = paste0("N = ", length(unique(AdvisedTrial$pid))))

ggplot(peek, aes(x = agentEffectSize, y = p.value, colour = parameter)) +
  geom_hline(yintercept = .05) + 
  geom_smooth(method = 'lm') +
  stat_cor() + 
  geom_point() +
  scale_y_continuous(limits = c(0, 1)) +
  labs(title = "p-value for influence t-test",
       subtitle = paste0("N = ", length(unique(AdvisedTrial$pid))))

```
